[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/auth-callback.html"
  to = "/auth-callback.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
